services:
  - type: web
    name: horilla-hrm
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: python manage.py migrate && gunicorn horilla.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        sync: false
      - key: CSRF_TRUSTED_ORIGINS
        sync: false
      - key: TIME_ZONE
        value: Asia/Kolkata
      - key: DB_INIT_PASSWORD
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: horilla-db
          property: connectionString
      - key: DB_ENGINE
        value: django.db.backends.postgresql

databases:
  - name: horilla-db
    plan: free
    databaseName: horilla
    user: horilla
